[package]
name = "variables"
version = "2.3.4"
authors = ["Emre Erg√ºn <emreergun@engramsoft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
